insert into products (title, price, remainder) values ('Title 1', 20, 10);
insert into products (title, price, remainder) values ('Title 2', 20, 10);
insert into products (title, price, remainder) values ('Title 3', 20, 10);
insert into products (title, price, remainder) values ('Title 4', 20, 10);
insert into products (title, price, remainder) values ('Title 5', 20, 10);
insert into products (title, price, remainder) values ('Title 6', 20, 10);
insert into products (title, price, remainder) values ('Title 7', 20, 10);
insert into products (title, price, remainder) values ('Title 8', 20, 10);
insert into products (title, price, remainder) values ('Title 9', 20, 10);
insert into products (title, price, remainder) values ('Title 10', 20, 10);
insert into products (title, price, remainder) values ('Title 11', 20, 10);
insert into products (title, price, remainder) values ('Title 12', 20, 10);
insert into products (title, price, remainder) values ('Title 13', 20, 10);
insert into products (title, price, remainder) values ('Title 14', 20, 10);
insert into products (title, price, remainder) values ('Title 15', 20, 10);
insert into products (title, price, remainder) values ('Title 16', 20, 10);
insert into products (title, price, remainder) values ('Title 17', 20, 10);
insert into products (title, price, remainder) values ('Title 18', 20, 10);
insert into products (title, price, remainder) values ('Title 19', 20, 10);
insert into products (title, price, remainder) values ('Title 20', 20, 10);

--select ord_pr.* from (select pr.* from products pr order by pr.product_id desc) ord_pr where row <= 10;