INSERT INTO subjects (subject_id, name, description) VALUES (8, 'Jellyfish Jam', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (14, 'Брайан Болланд', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (16, 'Брайан К. Вон', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (17, 'Фиона Стэплз', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (19, 'Тони Мур', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (21, 'Оливер Койпель', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (22, 'Мэтт Фрэкшн', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (23, 'Дэвид Аха', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (25, 'Ли Бермехо', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (26, 'Пиа Гуэрра', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (28, 'Стив Макнивен', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (29, 'Фрэнсис Манапул', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (30, 'Брайан Буччеллато', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (31, 'Джеф Лоэб', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (32, 'Тим Сэйл', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (6, 'Азбука', 'Издательская группа «Азбука-Аттикус» — одна из крупнейших книгоиздательских групп в России. По оценке Российской книжной палаты в 2016 году группа заняла 5-е место по количеству выпущенных наименований книг');
INSERT INTO subjects (subject_id, name, description) VALUES (1, 'DC Comics', 'DC Comics (основано в 1934 как National Allied Publications) — одно из крупнейших и наиболее популярных издательств комиксов. Издательство было куплено компанией «Warner Bros. Entertainment» в 1969. «DC Comics» издают продукцию, характеризующуюся наличием большого количества широко известных персонажей. В том числе «Супермен», «Бэтмен», «Чудо-женщина», «Зелёный Фонарь», «Флэш», «Аквамен», «Шазам», «Человек-ястреб», «Зелёная стрела», «Джон Константин», «Затанна» и др. В вымышленной вселенной «DC» также имеются команды, такие, как «Лига Справедливости», «Общество Справедливости Америки», «Юные Титаны», «Хранители», и известные злодеи, такие как «Джокер», «Лекс Лютор», «Женщина-кошка», «Дарксайд», «Рас аль Гул», «Детстроук», «Харли Квинн», «Синестро», «Профессор Зум», «Чёрный Адам», «Думсдэй» и «Брейниак»[3].');
INSERT INTO subjects (subject_id, name, description) VALUES (2, 'Marvel', 'Marvel Comics (от англ. marvel — чудо) — американская компания, издающая комиксы, подразделение корпорации «Marvel Entertainment». Получившая среди поклонников комиксов прозвище «Дом идей», «Marvel» наиболее известна такими сериями комиксов, как «Фантастическая четвёрка», «Человек-паук», «Невероятный Халк», «Железный человек», «Сорвиголова», «Серебряный Сёрфер», «Призрачный гонщик», «Доктор Стрэндж», «Тор», «Капитан Америка», «Люди Икс», «Каратель» и «Дэдпул». Большинство персонажей комиксов «Marvel» обитают в одной вымышленной вселенной, получившей название Земля-616.');
INSERT INTO subjects (subject_id, name, description) VALUES (3, 'Vertigo', 'Vertigo — импринт американского издательства комиксов DC Comics. Выпускает продукцию, ориентированную на более взрослую аудиторию и часто содержащую сцены насилия, злоупотребление алкоголем или наркотиками, а также откровенное (но не явное) изображение сексуальности, богохульства и спорных вопросов. Кроме комиксов ужасов и фэнтези, также публикует произведения в жанрах детектива, социальной сатиры и биографии. Каждый комикс издательства маркируется надписью: «Предназначено для взрослых читателей» (независимо от содержимого конкретного комикса).');
INSERT INTO subjects (subject_id, name, description) VALUES (11, 'Азбука-Аттикус', 'Издательская группа «Азбука-Аттикус» — одна из крупнейших книгоиздательских групп в России. По оценке Российской книжной палаты в 2016 году группа заняла 5-е место по количеству выпущенных наименований книг');
INSERT INTO subjects (subject_id, name, description) VALUES (4, 'Image Comics', 'Image comics — американское издательство комиксов. Его особенность в том, что авторы персонажей оставляют за собой права на этих персонажей, а не передают их издательству, как это делается в крупных компаниях. Является одним из 4 крупнейших издательств комиксов (наряду с Marvel, DC Comics, Dark Horse).');
INSERT INTO subjects (subject_id, name, description) VALUES (9, 'XL Media', 'XL Media (ЭксЭл Медиа) — дистрибьютор аниме в России, на Украине, в Белоруссии, Казахстане, Эстонии, Латвии и Литве. Компания декларирует своей основной задачей продвижение и популяризацию аниме на территории России, обеспечение максимальной доступности аниме для большинства русскоязычных почитателей.');
INSERT INTO subjects (subject_id, name, description) VALUES (10, 'Эксмо', 'Издательство «Эксмо́» — российская издательская компания, основанная Олегом Новиковым и Андреем Гредасовым в 1991 году. Генеральный директор — Олег Новиков. Издательство быстро вышло в лидеры рынка, благодаря сотрудничеству с популярными авторами, такими как Александра Маринина, Илья Деревянко, Дарья Донцова. Среди известных серий издательства — «Иронический детектив», «Чёрный котёнок», «Золотая серия поэзии» и др.');
INSERT INTO subjects (subject_id, name, description) VALUES (33, 'Шон Гордон Мёрфи', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (34, 'Джейсон М. Хаф', NULL);
INSERT INTO subjects (subject_id, name, description) VALUES (35, 'Комиксы', 'Русскоязычные издания комиксов');
INSERT INTO subjects (subject_id, name, description) VALUES (5, 'Dark Horse', 'Dark Horse Comics (с англ. «тёмная лошадка») — одно из крупнейших независимых издательств в США, специализирующееся на комиксах и манге. Основано в 1986 году Майком Ричардсоном, который к тому времени уже владел несколькими магазинами в штате Орегон и занимался продажей комиксов. Именно на доходы с магазинов он и основал Dark Horse Comics. С тех пор издательство расширялось и развивалось, и в настоящее время борется за третье место среди издателей комиксов с компаниями Image Comics и IDW Publishing.Наиболее известными комиксами, выходящими в Dark Horse Comics, стали: «Город грехов» (англ. Sin City) Фрэнка Миллера, Hellboy, цикл комиксов по «Звёздным войнам», «Баффи» (англ. Buffy the Vampire Slayer), Aliens, Конану, Кинг-Конгу (англ. King Kong), «300» (по этому комиксу был снят фильм «300 спартанцев»), Escapist, «Маска» (фильм «Маска»), а также манга Akira. Название «Тёмная лошадка» пришло не случайно. Marvel и DC Comics были олицетворением мира комиксов на рынке, и независимые издатели, пытавшиеся бороться против этих корпоративных гигантов, часто подавлялись возникающими трудностями.[2]');
INSERT INTO subjects (subject_id, name, description) VALUES (7, 'Комильфо', 'Мы издаём необычные, весёлые и красочные комиксы и книги, делаем это профессионально и любим своё дело.');
INSERT INTO subjects (subject_id, name, description) VALUES (13, 'Алан Мур', 'Алан Мур (англ. Alan Moore, род. 18 ноября 1953) — английский писатель, известный, прежде всего, работой в комиксах. Создал ряд произведений, положительно отмеченных критиками. Среди них: «Хранители» (англ. Watchmen), «V — значит Вендетта» (англ. V for Vendetta).');
INSERT INTO subjects (subject_id, name, description) VALUES (15, 'Арт Шпигельман', 'Арт Шпигельман (англ. Art Spiegelman; 15 февраля 1948, Стокгольм) — американский художник и писатель, автор и издатель романов-комиксов. Наиболее известен по комиксу «Маус», получившему Пулитцеровскую премию.');
INSERT INTO subjects (subject_id, name, description) VALUES (18, 'Роберт Киркман', 'Ро́берт Ки́ркман (англ. Robert Kirkman; род. 30 ноября 1978 года, Ричмонд (англ.)русск., Кентукки, США) — американский писатель, автор комиксов, наиболее известный своей работой над серией комиксов Ходячие мертвецы[1] и Invincible[2] для Image Comics и Marvel Team-Up и Marvel Zombies для Marvel Comics. ');
INSERT INTO subjects (subject_id, name, description) VALUES (20, 'Брайан Бендис', 'Брайан Майкл Бендис (англ. Brian Michael Bendis, род. 18 августа 1967, Кливленд, Огайо, США) — американский писатель, сценарист, автор комиксов и бывший художник. Завоевал признание критиков своими работами для Image Comics, Marvel Comics, а также самиздатом, является лауреатом пяти премий Уилла Айснера и является одним из самых успешных писателей комиксов в течение последних десяти лет.');
INSERT INTO subjects (subject_id, name, description) VALUES (24, 'Брайан Азарелло', 'Брайан Азарелло (англ. Brian Azzarello) — американский автор комиксов. Родился 11 августа 1962 года в Кливленде, штат Огайо. Стал известным благодаря серии комиксов о преступности «100 Bullets», изданной DC Comics в импринте Vertigo, рассчитанном под взрослую аудиторию. В 2011 году стал одним из сценаристов перезапущенной серии о Чудо-женщине.');
INSERT INTO subjects (subject_id, name, description) VALUES (27, 'Марк Миллар', 'Марк Ми́ллар (англ. Mark Millar; род. 24 декабря 1969, Котбридж, Северный Ланаркшир, Шотландия) — шотландский автор комиксов с середины 1990-х годов работающий с крупнейшими американскими издательствами, в основном с Marvel Comics. Одной из его наиболее известных работ является комикс «Пипец», экранизированный в 2010 году Мэттью Воном.');
INSERT INTO subjects (subject_id, name, description) VALUES (36, 'Манга', 'Русскоязычные издания манги');
INSERT INTO subjects (subject_id, name, description) VALUES (38, 'Артбуки и Энциклопедии', 'Большие и красивые справочные книги');
INSERT INTO subjects (subject_id, name, description) VALUES (39, 'Англоязычные издания', 'Оригинальные комиксы и книги на английском языке');
INSERT INTO subjects (subject_id, name, description) VALUES (37, 'Книги', 'Художественная и аналитическая литература, связанная с поп-культурой');
INSERT INTO subjects (subject_id, name, description) VALUES (46, 'Funko POP!', 'Оригинальная продукция от компании Funko');
INSERT INTO subjects (subject_id, name, description) VALUES (47, 'АСТ', NULL);
insert into subjects
values (48, 'Bubble', '«Bubble Comics» — российский издательский дом, специализирующийся на комиксах, созданный журналистом Артёмом Габреляновым в 2011 году[2]. Является крупнейшим издательством комиксов в России');
INSERT INTO subjects (subject_id, name, description) VALUES (49, 'Stickeriscoming', 'Производитель наклеек');
INSERT INTO subjects (subject_id, name, description)
VALUES (50, 'Фигурки', 'Различные фигурки для поклонников поп-культуры');
INSERT INTO subjects (subject_id, name, description)
VALUES (51, 'Стикеры', 'Наклейки с любимыми героями');
INSERT INTO subjects (subject_id, name, description)
VALUES (52, 'Напитки и сладости', 'Съедобные штуки для всех');
INSERT INTO subjects (subject_id, name, description)
VALUES (53, 'Брелоки', null);